/* pngcrush.h */

/* Copyright (C) 1998-2002, 2006-2016 Glenn Randers-Pehrson
 * This software is released under a license derived from the
 * libpng license (see LICENSE, in pngcrush.c).
 */

/* Special defines for pngcrush version 1.8.1 */

#ifndef PNGCRUSH_H
#define PNGCRUSH_H

/* Do not build stuff we will not use */
#undef PNG_BUILD_GRAYSCALE_PALETTE_SUPPORTED
#undef PNG_CONVERT_tIME_SUPPORTED
#undef PNG_EASY_ACCESS_SUPPORTED
/* #undef PNG_FIXED_POINT_SUPPORTED */
#undef PNG_INCH_CONVERSIONS_SUPPORTED
#undef PNG_INFO_IMAGE_SUPPORTED
#undef PNG_READ_PNG_SUPPORTED
#undef PNG_IO_STATE_SUPPORTED
#undef PNG_PROGRESSIVE_READ_SUPPORTED
#undef PNG_READ_ALPHA_MODE_SUPPORTED
#undef PNG_READ_BGR_SUPPORTED
#undef PNG_READ_COMPOSITE_NODIV_SUPPORTED
#define PNG_ERROR_TEXT_SUPPORTED
#define PNG_READ_STRIP_16_TO_8_SUPPORTED
#undef PNG_READ_SWAP_ALPHA_SUPPORTED
#undef PNG_READ_SWAP_SUPPORTED
#undef PNG_READ_INVERT_ALPHA_SUPPORTED
#undef PNG_READ_INVERT_SUPPORTED
#undef PNG_READ_PACKSWAP_SUPPORTED
#undef PNG_READ_QUANTIZE_SUPPORTED
#undef PNG_READ_USER_CHUNKS_SUPPORTED
#undef PNG_USER_CHUNKS_SUPPORTED
#undef PNG_TIME_RFC1123_SUPPORTED
#undef PNG_WRITE_PNG_SUPPORTED
#undef PNG_WRITE_BGR_SUPPORTED
#undef PNG_WRITE_GET_PALETTE_MAX_SUPPORTED
#undef PNG_WRITE_INVERT_ALPHA_SUPPORTED
#undef PNG_WRITE_INVERT_SUPPORTED
#undef PNG_WRITE_OPTIMIZE_CMF_SUPPORTED
#undef PNG_WRITE_SWAP_ALPHA_SUPPORTED
#undef PNG_WRITE_SWAP_SUPPORTED
#undef PNG_WRITE_WEIGHTED_FILTER_SUPPORTED

#undef PNG_SIMPLIFIED_READ_AFIRST_SUPPORTED
#undef PNG_SIMPLIFIED_READ_BGR_SUPPORTED
#undef PNG_SIMPLIFIED_READ_SUPPORTED
#undef PNG_SIMPLIFIED_WRITE_AFIRST_SUPPORTED
#undef PNG_SIMPLIFIED_WRITE_BGR_SUPPORTED
#undef PNG_SIMPLIFIED_WRITE_SUPPORTED

#endif /* !PNGCRUSH_H */
